# Generated by Django 5.2 on 2025-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiphishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
