# Generated by Django 5.2 on 2025-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiphishing', '0002_detectionresult_email_detectionresult_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionresult',
            name='email',
        ),
        migrations.RemoveField(
            model_name='detectionresult',
            name='url',
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='email_file',
            field=models.FileField(blank=True, null=True, upload_to='emails/'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='texts/'),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='url_file',
            field=models.FileField(blank=True, null=True, upload_to='urls/'),
        ),
    ]
